@extends('layouts.admin')

@section('title', $short->exists ? 'Editar Short' : 'Novo Short')

@section('content')
<section class="max-w-4xl">
 <div class="mb-7 flex items-center gap-3"><a href="{{ route('admin.shorts.index') }}" class="w-10 h-10 rounded-full border border-neutral-700 grid place-items-center"><i class="fa-solid fa-arrow-left"></i></a><div><h2 class="text-2xl font-bold">{{ $short->exists ? 'Editar Short' : 'Novo Short' }}</h2><p class="text-sm text-neutral-500">Links diretos são testados; plataformas externas usam o player oficial.</p></div></div>
 @if($errors->any())<div class="mb-5 p-4 rounded-xl bg-red-950/30 text-red-300">{{ $errors->first() }}</div>@endif
 @if(session('success'))<div class="mb-5 p-4 rounded-xl bg-green-950/30 text-green-300">{{ session('success') }}</div>@endif
 <form method="POST" action="{{ $short->exists ? route('admin.shorts.update', $short) : route('admin.shorts.store') }}" class="space-y-6 bg-neutral-900 border border-neutral-800 rounded-2xl p-6">@csrf @if($short->exists) @method('PUT') @endif
   <div class="grid md:grid-cols-2 gap-5"><label class="space-y-2"><span class="text-xs text-neutral-400">TÍTULO</span><input required name="title" value="{{ old('title', $short->title) }}" class="w-full input-dark bg-black border border-neutral-700 rounded-xl px-4 py-3"></label><label class="space-y-2"><span class="text-xs text-neutral-400">CATEGORIA</span><input name="category" value="{{ old('category', $short->category) }}" class="w-full bg-black border border-neutral-700 rounded-xl px-4 py-3"></label></div>
   <label class="block space-y-2"><span class="text-xs text-neutral-400">URL DA FONTE</span><input required type="url" id="source_url" name="source_url" value="{{ old('source_url', $short->source_url) }}" placeholder="YouTube, TikTok, DailyMotion, Drive ou MP4/HLS próprio" class="w-full bg-black border border-neutral-700 rounded-xl px-4 py-3 text-sm font-mono"><button type="button" id="inspect" class="mt-3 text-sm border border-neutral-700 px-4 py-2 rounded-lg">Verificar fonte</button><div id="inspect-result" class="text-xs text-neutral-400 mt-2"></div></label>
   <div class="grid md:grid-cols-3 gap-5"><label class="space-y-2"><span class="text-xs text-neutral-400">CAPA (OPCIONAL)</span><input type="url" name="thumbnail_url" value="{{ old('thumbnail_url', $short->thumbnail_url) }}" class="w-full bg-black border border-neutral-700 rounded-xl px-4 py-3"></label><label class="space-y-2"><span class="text-xs text-neutral-400">DURAÇÃO (SEG.)</span><input type="number" min="0" name="duration_seconds" value="{{ old('duration_seconds', $short->duration_seconds) }}" class="w-full bg-black border border-neutral-700 rounded-xl px-4 py-3"></label><label class="space-y-2"><span class="text-xs text-neutral-400">IDIOMA</span><input name="language" value="{{ old('language', $short->language ?: 'pt-BR') }}" class="w-full bg-black border border-neutral-700 rounded-xl px-4 py-3"></label></div>
   <label class="block space-y-2"><span class="text-xs text-neutral-400">DESCRIÇÃO</span><textarea name="description" rows="4" class="w-full bg-black border border-neutral-700 rounded-xl p-4">{{ old('description', $short->description) }}</textarea></label><label class="block space-y-2"><span class="text-xs text-neutral-400">HASHTAGS</span><input name="hashtags" value="{{ old('hashtags', $short->hashtags) }}" placeholder="#filmes #curiosidades" class="w-full bg-black border border-neutral-700 rounded-xl px-4 py-3"></label>
   <div class="border border-neutral-800 rounded-xl p-4 space-y-3"><div><span class="text-xs text-neutral-400">CONTEÚDO RELACIONADO (OPCIONAL)</span><p class="text-xs text-neutral-500 mt-1">Busque um filme, série ou temporada para vincular a este Short.</p></div><input id="related-search" autocomplete="off" placeholder="Buscar filme, série ou temporada..." class="w-full bg-black border border-neutral-700 rounded-xl px-4 py-3"><input type="hidden" name="related_type" id="related-type" value="{{ old('related_type', $short->related_type) }}"><input type="hidden" name="related_id" id="related-id" value="{{ old('related_id', $short->related_id) }}"><div id="related-selected" class="{{ $short->related_title ? '' : 'hidden' }} bg-netflix/10 border border-netflix/30 rounded-lg p-3 text-sm"><span id="related-selected-text">{{ $short->related_title }}</span><button type="button" id="clear-related" class="float-right text-red-300">Remover</button></div><div id="related-results" class="hidden max-h-56 overflow-y-auto border border-neutral-800 rounded-xl"></div></div>
   <label class="flex gap-3 items-center"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $short->exists ? $short->is_active : true))><span>Publicar no feed</span></label>
   @if($short->exists)<div class="p-4 bg-black rounded-xl text-sm"><b>Diagnóstico:</b> {{ $short->source_provider }} · {{ $short->playback_kind }} · {{ $short->availability }}<div class="text-neutral-400 mt-1">{{ $short->availability_message }}</div></div>@endif
   <button class="bg-netflix font-bold px-6 py-3 rounded-xl">Salvar Short</button>
 </form>
</section>
@endsection
@push('scripts')<script>
document.getElementById('inspect').onclick=async()=>{const u=document.getElementById('source_url').value,r=document.getElementById('inspect-result');r.textContent='Verificando...';try{const x=await fetch('{{ route('admin.shorts.inspect') }}?url='+encodeURIComponent(u));const d=await x.json();r.textContent=`${d.source_provider} · ${d.playback_kind} · ${d.availability}: ${d.availability_message}`}catch(e){r.textContent='Não foi possível verificar a URL.'}};
const relatedSearch=document.getElementById('related-search'), results=document.getElementById('related-results'), selected=document.getElementById('related-selected'), selectedText=document.getElementById('related-selected-text'); let timer;
relatedSearch.addEventListener('input',()=>{clearTimeout(timer);const q=relatedSearch.value.trim();if(q.length<2){results.classList.add('hidden');return}timer=setTimeout(async()=>{const res=await fetch('{{ route('admin.shorts.search-related') }}?q='+encodeURIComponent(q));const items=await res.json();results.replaceChildren();items.forEach(item=>{const b=document.createElement('button');b.type='button';b.className='block w-full text-left px-4 py-3 hover:bg-neutral-800 border-b border-neutral-800 last:border-0';b.textContent=`${item.title} — ${item.subtitle}`;b.onclick=()=>{document.getElementById('related-type').value=item.type;document.getElementById('related-id').value=item.id;selectedText.textContent=item.title;selected.classList.remove('hidden');results.classList.add('hidden');relatedSearch.value=''};results.appendChild(b)});results.classList.toggle('hidden',items.length===0)},250)});
document.getElementById('clear-related').onclick=()=>{document.getElementById('related-type').value='';document.getElementById('related-id').value='';selected.classList.add('hidden')};
</script>@endpush
